### ISSUE TITLE
EKS backend may fail to supply public_ip

### ISSUE THREAD

**Issue by andreas-kupries** [SUSE/catapult#189]
The command `PUBLIC_IP="$(kubectl get nodes -o json | jq -r '.items[].status.addresses[] | select(.type == "InternalIP").address' | head -n 1)"` in `backend/eks/deploy.sh` is not robust.

During a trial of standing up a cluster with kube cf (& tear down) today a failure to deploy `kubecf` could be traced to this command returning an empty string and baking that value into the `cap-values` config-map.
The second attempt of bringing up the cluster then was ok. It looks as if there is some racing involved.

I recommend to retry this command when it returns the empty string. Every 5 seconds, at most 12 times (1 minute) should be enough, with proper panic if the limit is reached.

**Comment by viccuad** [comment]
I suppose this happens because the cluster worker nodes are not up when we go though asking for the internal ip.

On GKE we solve this by waiting for the cluster to be up, with:
https://github.com/SUSE/catapult/blob/0a43cf2204a5c3601a1958f1bca11e2dea78aab5/backend/gke/deploy.sh#L82-L83


On AKS, just commited: https://github.com/SUSE/catapult/pull/196/commits/5216f18ac3031843b1784a78be45a9adcf08807d

ON EKS, opened: https://github.com/SUSE/catapult/pull/203
