### ISSUE TITLE
`scf` target should have a wider scope

### ISSUE THREAD

**Issue by mudler** [SUSE/catapult#32]
The `scf` target currently is depending on the previous targets to deploy a scf installation. It would be better instead to have the **public** `scf` target which also takes care of the setup, so that `make scf` returns a deployed cluster (regardless of the backend) always.

e.g. We can rename the current `scf` target and make it private (e.g. `make deploy-scf` ) to just care of the helm bits and have a smarter oneliner "`make scf`" (which should become the public one, consumed by end-users).

**Comment by fargozhu** [comment]
@mudler can u describe a little bit more what you want to achieve?

**Comment by viccuad** [comment]
I think it's a good idea, but I need more convincing on my side.

I agree that we should provide a public `make scf` that does what `make chart gen-config scf login` does now; the user gets a working scf.
But I think getting a backend up also when doing `make scf` confuses the states (k8s backend -> scf -> tests), and is confusing when doing `make clean-scf`: do we remove scf only, or does the backend get removed too? Since we have terraform backends on public cloud, I would like to be as explicit as possible on when a backend gets created and when gets destroyed.

We could always have a `make all-scf` or `make all-backend` that achieves the full stack deployed. Wdyt?

**Comment by mudler** [comment]
> I think it's a good idea, but I need more convincing on my side.
> 
> I agree that we should provide a public `make scf` that does what `make chart gen-config scf login` does now; the user gets a working scf.
> But I think getting a backend up also when doing `make scf` confuses the states (k8s backend -> scf -> tests), and is confusing when doing `make clean-scf`: do we remove scf only, or does the backend get removed too? 

IMHO it should be idempotent unless you explicitly call for states, e.g.: make all should give you a cluster with scf, regardless of the cluster_name=xxx is present or not (so if the k8s is up, just clean up scf and re-deploy, if k8s is not there, provide it and deploy) 

> Since we have terraform backends on public cloud, I would like to be as explicit as possible on when a backend gets created and when gets destroyed.
> 
> We could always have a `make all`, or a `make all-scf` or `make all-backend` that achieves the full stack deployed. Wdyt?
Yup exactly, I think that can be still left as an option very easily, just let's provide public API for each backend as well. But at the same time we restrict the "most used" to work transparently regardless of the backend, reducing the user cognitive load :)

**Comment by viccuad** [comment]
Seems that with the refactor to v2, `make all` and `make scf` give you a k8s + scf, or scf on top of an existing k8s, respectively.

The only point missing would be to give `make all` the functionality to not redeploy k8s/scf if already present. Right now, each of those targets clean first and then deploy.

**Comment by viccuad** [comment]
Closing as all of this was already achieved :tada:
