### ISSUE TITLE
source cluster .envrc outside buildir

### ISSUE THREAD

**Issue by mudler** [SUSE/catapult#53]
This is not anymore possible, and breaks many workflow I'm aware of.

**Comment by viccuad** [comment]
Instead of removing the HEREDOC_LITERAL from buildir.sh when constructing the .envrc, it should be possible to do something like:

Inside of envrc, calculate the absolute path of the .envrc and save it on a variable, with something like `dirname "$(readlink -f "$0")"`.
Use that variable to give value to the exported env vars paths.

That way, no matter from where you load the .envrc, you have a correct path, and if you move the buildir, you can reload the envrc to get the new path on the exported values.

Buut, I have failed with it on a couple tries.

**Comment by viccuad** [comment]
This seems to be more difficult than it looks at first view,
-  Needs to work when sourcing the script, and when direnv "loads" the script (spawns a bash subshell, executes the shell, captures the difference in env vars, exports the env vars outside).
-  Should not use readlink, as for eg. macos may not have it installed by default
-  We could use $BASH_SOURCE, but that's only present on bash v3+ (again, macos). Also, BASH_SOURCE has no value if sourced.
-  Should work if sourced from zsh or other shells
